reload-message: "&aReloaded Configuration!"
litebans-do-not-send-silent-punishments: true
debug-messages: true
#Permissions :
#Reload : bwh.reload

ban:
  enabled: true
  webhook-url: "enter-url-here"
  webhook-title: "New Ban!"
  webhook-thumbnail: "webhook-thumbnail-url-here"

mute:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Mute!"
  webhook-thumbnail: "webhook-thumbnail-url-here"

warn:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Warn!"
  webhook-thumbnail: "webhook-thumbnail-url-here"

kick:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Kick!"
  webhook-thumbnail: "webhook-thumbnail-url-here"