reload-message: "&aReloaded Configuration!"
litebans-do-not-send-silent-punishments: true

#Permissions :
#Reload : bwh.reload

ban:
  options:
    send-enabled: true
    embed-color: "red"
    thumbnail:
      enabled: false
      url: "url-here"
  webhook-settings:
    punished-by:
      name: "Banned By"
      value: "%operator%"
    username:
      name: "Username"
      value: %username%
    reason:
      name: "Reason"
      value: "%reason%"
    duration:
      name: "Duration"
      value: "%duration%"

ban1:
  enabled: true
  webhook-url: "enter-url-here"
  webhook-title: "New Ban!"
  webhook-thumbnail: "webhook-thumbnail-url-here"

mute:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Mute!"
  webhook-thumbnail: "webhook-thumbnail-url-here"

warn:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Warn!"
  webhook-thumbnail: "webhook-thumbnail-url-here"

kick:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Kick!"
  webhook-thumbnail: "webhook-thumbnail-url-here"