name: BansWebhook
version: ${project.version}
main: ir.pmzhero.banswebhook.spigot.BansWebhook
api-version: 1.13
softdepend: [LiteBans, AdvancedBan]
authors: [PmzHero]
description: Sends punishment info to a discord webhook
commands:
  bwh:
    permission: bwh.reload
    permission-message: No Permission!
    description: BansWebhook Main Command! /bwh reload
    aliases:
      - bwhspigot
    usage: /bwh <reload>